// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfk5W0mxdpUhCymPQg6gAmAIy3BvXEdY',
    appId: '1:470450489924:web:79fe277a74128954f30a11',
    messagingSenderId: '470450489924',
    projectId: 'path-finder-f586c',
    authDomain: 'path-finder-f586c.firebaseapp.com',
    storageBucket: 'path-finder-f586c.appspot.com',
    measurementId: 'G-V205ESR8B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo4Nd76sXu5wbZo297PdFe3RtlotPoNgE',
    appId: '1:470450489924:android:993fdfd89da63c32f30a11',
    messagingSenderId: '470450489924',
    projectId: 'path-finder-f586c',
    storageBucket: 'path-finder-f586c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1G2A_VAyAuemN18VpC6Ikzx3O523Fqzk',
    appId: '1:470450489924:ios:70f3889592b88213f30a11',
    messagingSenderId: '470450489924',
    projectId: 'path-finder-f586c',
    storageBucket: 'path-finder-f586c.appspot.com',
    iosBundleId: 'com.example.pathfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1G2A_VAyAuemN18VpC6Ikzx3O523Fqzk',
    appId: '1:470450489924:ios:70f3889592b88213f30a11',
    messagingSenderId: '470450489924',
    projectId: 'path-finder-f586c',
    storageBucket: 'path-finder-f586c.appspot.com',
    iosBundleId: 'com.example.pathfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjfk5W0mxdpUhCymPQg6gAmAIy3BvXEdY',
    appId: '1:470450489924:web:573aae677b0427b1f30a11',
    messagingSenderId: '470450489924',
    projectId: 'path-finder-f586c',
    authDomain: 'path-finder-f586c.firebaseapp.com',
    storageBucket: 'path-finder-f586c.appspot.com',
    measurementId: 'G-D7VCXRBLJQ',
  );
}
